### ISSUE TITLE
Login feature & Welcome page

### ISSUE THREAD

**Issue by JoshLuong** [JoshLuong/Trippo#4]
### Purpose:
Create the login feature/ UI and whole welcome page styling, as well as looking into the embedded Google login.

### QA: Acceptance Criteria Reviewer's Checklist

- [x] styling matches Figma prototype
- [x] it is responsive
- [x] buttons are click-able (although don't have to do anything right now)
- [x] there are no React errors/ warnings on console
- [x] works locally (in general and with resizing)

TODO :: 
- [ ] Add Google Signup/Sign in
- [ ] Fix Textfield outline colour (overwrite MUI component styling)

**Comment by rho1207** [comment]
- [ ] Add Google Signup/Sign in
- [ ] Fix Textfield outline colour (overwrite MUI component styling)
